(async()=>{
 const cfg=window.KORBUILD_SUPABASE;if(!cfg||!window.supabase)return;
 const c=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
 const $=id=>document.getElementById(id);let data=null;
 const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function toast(msg,type='success'){let x=document.querySelector('.kor-toast');if(!x){x=document.createElement('div');x.className='kor-toast';document.body.appendChild(x)}x.className='kor-toast show '+type;x.innerHTML='<span class="toast-icon">'+(type==='success'?'✓':'!')+'</span><span>'+msg+'</span>';clearTimeout(window.__aiToast);window.__aiToast=setTimeout(()=>x.classList.remove('show'),3000)}
 function status(x){if(!x.enabled)return ['DISABLED','disabled'];const pct=x.monthly_budget_usd>0?(x.monthly_used_usd/x.monthly_budget_usd)*100:0;if(pct>=100)return ['BLOCKED','blocked'];if(pct>=x.warn_percent)return ['ALERT','alert'];return ['ACTIVE','active']}
 async function load(){const {data:d,error}=await c.rpc('get_korbuild_ai_admin_data');if(error||!d){return}data=d;renderGlobal();renderCompanies();}
 function renderGlobal(){const g=data.global||{};$('ai-global-enabled').checked=g.enabled!==false;$('ai-global-budget').value=g.monthly_budget_usd??'';$('ai-global-warn').value=g.warn_percent??80;$('ai-global-hard').checked=g.hard_limit!==false;$('ai-global-rpm').value=g.max_requests_per_minute??30;$('ai-global-used').textContent=money(g.monthly_used_usd);$('ai-global-budget-label').textContent=money(g.monthly_budget_usd);const pct=g.monthly_budget_usd?Math.min(100,(g.monthly_used_usd/g.monthly_budget_usd)*100):0;$('ai-global-bar').style.width=pct+'%';$('ai-global-percent').textContent=pct.toFixed(1)+'%';}
 function renderCompanies(){const rows=data.companies||[];$('ai-companies-list').innerHTML=rows.map(x=>{const [label,cls]=status(x);const pct=x.monthly_budget_usd?Math.min(100,(x.monthly_used_usd/x.monthly_budget_usd)*100):0;return `<div class="ai-company-row" data-id="${x.empresa_id}"><div class="ai-company-main"><strong>${esc(x.company_name)}</strong><small>${esc(x.country||'')} · ${x.monthly_requests_used} requests this month</small></div><div><span class="ai-status ${cls}">${label}</span></div><div class="ai-usage"><div><b>${money(x.monthly_used_usd)}</b> / ${money(x.monthly_budget_usd)}</div><div class="ai-bar"><i style="width:${pct}%"></i></div><small>${pct.toFixed(1)}% used</small></div><button type="button" class="ai-edit" data-id="${x.empresa_id}">Configure</button></div>`}).join('')||'<p>No active companies found.</p>';document.querySelectorAll('.ai-edit').forEach(b=>b.onclick=()=>openCompany(b.dataset.id));}
 function openCompany(id){const x=(data.companies||[]).find(v=>v.empresa_id===id);if(!x)return;$('ai-company-id').value=x.empresa_id;$('ai-company-name').textContent=x.company_name;$('ai-company-enabled').checked=x.enabled!==false;$('ai-company-budget').value=x.monthly_budget_usd;$('ai-company-monthly-limit').value=x.monthly_request_limit;$('ai-company-daily-limit').value=x.daily_request_limit;$('ai-company-output').value=x.max_output_tokens;$('ai-company-request-cost').value=x.max_cost_per_request_usd;$('ai-company-warn').value=x.warn_percent;$('ai-company-hard').checked=x.hard_limit!==false;$('ai-company-modal').classList.add('open');}
 function closeCompany(){$('ai-company-modal').classList.remove('open')}
 $('ai-company-close').onclick=closeCompany;$('ai-company-cancel').onclick=closeCompany;$('ai-company-modal').addEventListener('click',e=>{if(e.target===$('ai-company-modal'))closeCompany()});
 $('ai-global-form').onsubmit=async e=>{e.preventDefault();const {data:r,error}=await c.rpc('update_korbuild_ai_global_settings',{p_enabled:$('ai-global-enabled').checked,p_monthly_budget_usd:Number($('ai-global-budget').value),p_warn_percent:Number($('ai-global-warn').value),p_hard_limit:$('ai-global-hard').checked,p_max_requests_per_minute:Number($('ai-global-rpm').value)});if(error||!r){toast(error?.message||'Unable to save AI settings','error');return}await load();toast('Global AI controls updated.')};
 $('ai-company-form').onsubmit=async e=>{e.preventDefault();const {data:r,error}=await c.rpc('update_korbuild_ai_company_limit',{p_empresa_id:$('ai-company-id').value,p_enabled:$('ai-company-enabled').checked,p_monthly_budget_usd:Number($('ai-company-budget').value),p_monthly_request_limit:Number($('ai-company-monthly-limit').value),p_daily_request_limit:Number($('ai-company-daily-limit').value),p_max_output_tokens:Number($('ai-company-output').value),p_max_cost_per_request_usd:Number($('ai-company-request-cost').value),p_warn_percent:Number($('ai-company-warn').value),p_hard_limit:$('ai-company-hard').checked});if(error||!r){toast(error?.message||'Unable to save company AI limits','error');return}closeCompany();await load();toast('Company AI franchise updated.')};
 $('ai-refresh').onclick=load;await load();
})();