if(!window.KORBUILD_APP){const s=document.createElement('script');s.src='app-config.js?v=1.2';document.head.appendChild(s);}
const { url, publishableKey } = window.KORBUILD_SUPABASE;
const db = window.supabase.createClient(url, publishableKey, { auth: { persistSession: true, autoRefreshToken: true } });
const $=id=>document.getElementById(id); const state={empresaId:null,editingId:new URLSearchParams(location.search).get('id'),teams:[]};
function closeMenu(){$('user-menu')?.classList.add('hidden');$('user-menu-btn')?.setAttribute('aria-expanded','false');}
function showMessage(text,type='success'){const el=$('message');el.textContent=text;el.className=`message ${type}`;el.classList.remove('hidden');}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function loadProfile(){const{data:{session},error}=await db.auth.getSession();if(error||!session?.user){location.href='index.html';return false;}const{data:profile,error:profileError}=await db.from('usuarios').select('id,name,empresa_id,active,empresas(name)').eq('id',session.user.id).maybeSingle();if(profileError||!profile?.empresa_id){showMessage(profileError?.message||'Unable to load workspace profile.','error');return false;}state.empresaId=profile.empresa_id;const company=profile.empresas?.name||'KORbuild Demo';$('side-company').textContent=company;const profileName=profile.name?.trim();const name=profileName&&profileName!=='Owner'?profileName:session.user.user_metadata?.full_name||`${company} Owner`;const initial=name.trim().charAt(0).toUpperCase()||'O';$('user-name').textContent=name;$('user-email').textContent=session.user.email||'';$('user-avatar').textContent=initial;$('menu-avatar').textContent=initial;$('menu-full-name').textContent=name;$('menu-full-email').textContent=session.user.email||'';return true;}
async function loadTeams(){const{data,error}=await db.from('equipes').select('id,name,active').eq('empresa_id',state.empresaId).eq('active',true).order('name',{ascending:true});if(error){showMessage(`Unable to load teams. ${error.message}`,'error');return false;}state.teams=data||[];const select=$('person-team');select.innerHTML='<option value="">Select a team</option>'+state.teams.map(t=>`<option value="${t.id}">${escapeHtml(t.name)}</option>`).join('');if(!state.teams.length){select.disabled=true;$('save-person').disabled=true;showMessage('Create at least one active team before adding a person.','error');return false;}select.disabled=false;return true;}
async function loadPerson(){if(!state.editingId)return;const{data,error}=await db.from('colaboradores').select('id,name,specialty,active,equipe_id').eq('id',state.editingId).eq('empresa_id',state.empresaId).maybeSingle();if(error||!data){showMessage(error?.message||'Person not found.','error');return;}$('person-id').value=data.id;$('person-name').value=data.name||'';$('person-specialty').value=data.specialty||'';$('person-active').checked=data.active;$('person-team').value=data.equipe_id||'';$('form-eyebrow').textContent='EDIT PERSON';$('form-title').textContent='Edit person';$('page-title').textContent='Edit Person';$('save-person').textContent='Save Changes';}
async function savePerson(event){event.preventDefault();const name=$('person-name').value.trim();const specialty=$('person-specialty').value.trim()||null;const equipeId=$('person-team').value;const active=$('person-active').checked;if(!name){showMessage('Name is required.','error');return;}if(!equipeId){showMessage('A Team is required before a person can be saved.','error');return;}const btn=$('save-person');btn.disabled=true;btn.textContent='Saving...';try{let error;if(state.editingId){({error}=await db.from('colaboradores').update({name,specialty,equipe_id:equipeId,active,updated_at:new Date().toISOString()}).eq('id',state.editingId).eq('empresa_id',state.empresaId));}else{({error}=await db.from('colaboradores').insert({empresa_id:state.empresaId,name,specialty,equipe_id:equipeId,active}));}if(error)throw error;showMessage(state.editingId?'Person updated successfully.':'Person added successfully.');setTimeout(()=>location.href='people.html',500);}catch(error){showMessage(`We couldn't save this person. ${error.message||'Please try again.'}`,'error');btn.disabled=false;btn.textContent=state.editingId?'Save Changes':'Save Person';}}
$('user-menu-btn')?.addEventListener('click',e=>{e.stopPropagation();const menu=$('user-menu');const hidden=menu.classList.toggle('hidden');$('user-menu-btn').setAttribute('aria-expanded',String(!hidden));});document.addEventListener('click',e=>{if(!e.target.closest('.user-menu-wrap'))closeMenu();});$('menu-logout')?.addEventListener('click',async()=>{await db.auth.signOut();location.href='index.html';});$('person-form').addEventListener('submit',savePerson);
async function init(){if(!(await loadProfile()))return;if(!(await loadTeams()))return;await loadPerson();}init();