const {url,publishableKey}=window.KORBUILD_SUPABASE;const db=window.supabase.createClient(url,publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let empresaId=null,cycle=null,config=null;
const dayNum={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function fmtDate(s){return new Date(s+'T00:00:00').toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'})}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function dateOnly(d){return d.toISOString().slice(0,10)}
function nextDayOnOrAfter(date,target){const d=new Date(date);const delta=(target-d.getDay()+7)%7;d.setDate(d.getDate()+delta);return d}
function cycleStartDate(){return new Date(cycle.year,Number(cycle.start_month)-1,1)}
function cycleEndDate(){return new Date(cycle.year,Number(cycle.end_month),0)}
function showMessage(text,error=false){const m=$('message');m.textContent=text;m.classList.remove('hidden','error');if(error)m.classList.add('error')}
function renderPeriods(rows){const body=$('period-list');if(!rows.length){body.innerHTML='<tr><td colspan="4" class="empty">No periods have been prepared yet.</td></tr>';return}body.innerHTML=rows.map((p,i)=>`<tr><td><strong>Week ${p.week_number??i+1}</strong></td><td>${fmtDate(p.start_date)} → ${fmtDate(p.end_date)}</td><td><span class="period-status">${p.status||'OPEN'}</span></td><td>${p.created_at?new Date(p.created_at).toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'}):'—'}</td></tr>`).join('')}
async function load(){const{data:{session},error:se}=await db.auth.getSession();if(se||!session?.user){location.href='index.html';return}const{data:user,error:ue}=await db.from('usuarios').select('id,name,empresa_id,empresas(name)').eq('id',session.user.id).maybeSingle();if(ue||!user?.empresa_id){showMessage('Unable to load workspace profile.',true);return}empresaId=user.empresa_id;const name=user.name||session.user.user_metadata?.full_name||'Owner';const initial=name.trim().charAt(0).toUpperCase()||'O';$('user-name').textContent=name;$('user-email').textContent=session.user.email||'';$('user-avatar').textContent=initial;$('menu-avatar').textContent=initial;$('menu-full-name').textContent=name;$('menu-full-email').textContent=session.user.email||'';
 const[cr,br]=await Promise.all([db.from('configuracoes_operacionais').select('*').eq('empresa_id',empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle(),db.from('bonus_cycles').select('*').eq('empresa_id',empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(cr.error||br.error){showMessage('Unable to load cycle configuration.',true);return}config=cr.data;cycle=br.data;if(!cycle){$('cycle-name').textContent='No Bonus Cycle configured';$('cycle-meta').textContent='Complete Workspace Setup before preparing a period.';$('prepare-btn').disabled=true;renderPeriods([]);return}const frequency=config?.evaluation_frequency||'WEEKLY';$('cycle-name').textContent=cycle.name;$('cycle-meta').textContent=`${cycle.year} · ${new Date(cycle.year,cycle.start_month-1).toLocaleDateString('en-US',{month:'long'})} → ${new Date(cycle.year,cycle.end_month-1).toLocaleDateString('en-US',{month:'long'})} · ${frequency==='WEEKLY'?'Weekly':frequency}`;$('cycle-status').textContent=cycle.status||'OPEN';$('starting-points').textContent=(cycle.starting_points??config?.starting_points??'—').toLocaleString?.('en-US')??'—';const people=await db.from('colaboradores').select('id,active').eq('empresa_id',empresaId);$('people-count').textContent=(people.data||[]).filter(p=>p.active).length;const periods=await db.from('periodos').select('id,start_date,end_date,year,week_number,status,created_at').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).order('start_date',{ascending:false});if(periods.error){showMessage(`Unable to load periods. ${periods.error.message}`,true);return}$('period-count').textContent=periods.data?.length||0;const active=(periods.data||[]).find(p=>p.status==='OPEN'||p.status==='ACTIVE');if(active){$('active-period').textContent=`Week ${active.week_number}`;$('active-dates').textContent=`${fmtDate(active.start_date)} → ${fmtDate(active.end_date)}`}else{$('active-period').textContent='—';$('active-dates').textContent='No period prepared'}renderPeriods(periods.data||[])}
async function prepareNextPeriod(){if(!cycle||!config){showMessage('Complete the Bonus Cycle and Evaluation Period configuration first.',true);return}const btn=$('prepare-btn');btn.disabled=true;btn.textContent='Preparing...';try{if(config.evaluation_frequency!=='WEEKLY')throw new Error('The first period generator supports Weekly cycles.');const existing=await db.from('periodos').select('id,start_date,end_date,week_number,status').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).order('end_date',{ascending:false}).limit(1).maybeSingle();if(existing.error)throw existing.error;let start;if(existing.data){start=new Date(existing.data.end_date+'T00:00:00');start.setDate(start.getDate()+1);start=nextDayOnOrAfter(start,Number(config.period_start_day))}else{start=nextDayOnOrAfter(cycleStartDate(),Number(config.period_start_day))}const end=new Date(start);let delta=(Number(config.period_end_day)-start.getDay()+7)%7;end.setDate(end.getDate()+delta);if(start>cycleEndDate()||end>cycleEndDate())throw new Error('There is no complete weekly period remaining inside this Bonus Cycle.');const startDate=dateOnly(start),endDate=dateOnly(end);const duplicate=await db.from('periodos').select('id').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).eq('start_date',startDate).maybeSingle();if(duplicate.error)throw duplicate.error;if(duplicate.data){showMessage(`Period ${fmtDate(startDate)} → ${fmtDate(endDate)} already exists.`);return}const nextWeek=isoWeek(start);const insert={empresa_id:empresaId,start_date:startDate,end_date:endDate,year:start.getFullYear(),week_number:nextWeek,status:'OPEN',bonus_cycle_id:cycle.id};const{error}=await db.from('periodos').insert(insert);if(error)throw error;showMessage(`Period created: ${fmtDate(startDate)} → ${fmtDate(endDate)}.`);await load()}catch(e){console.error(e);showMessage(e.message||'Unable to prepare the next period.',true)}finally{btn.disabled=false;btn.textContent='Prepare Next Period →'}}
$('prepare-btn').addEventListener('click',prepareNextPeriod);$('user-menu-btn').addEventListener('click',e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')});document.addEventListener('click',e=>{if(!e.target.closest('.user-menu-wrap'))$('user-menu').classList.add('hidden')});$('menu-logout').addEventListener('click',async()=>{await db.auth.signOut();location.href='index.html'});load();