const {url,publishableKey}=window.KORBUILD_SUPABASE;const db=window.supabase.createClient(url,publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let empresaId=null,cycle=null,config=null;
function fmtDate(s){return new Date(s+'T00:00:00').toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'})}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function dateOnly(d){return d.toISOString().slice(0,10)}
function nextDayOnOrAfter(date,target){const d=new Date(date);const delta=(target-d.getDay()+7)%7;d.setDate(d.getDate()+delta);return d}
function cycleStartDate(){return new Date(cycle.year,Number(cycle.start_month)-1,1)}
function cycleEndDate(){return new Date(cycle.year,Number(cycle.end_month),0)}
function todayLocal(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function nextConfiguredPeriodStart(){const today=todayLocal();const target=Number(config.period_start_day);const d=new Date(today);let delta=(target-d.getDay()+7)%7;if(delta===0)delta=7;d.setDate(d.getDate()+delta);const cycleStart=cycleStartDate();return d<cycleStart?nextDayOnOrAfter(cycleStart,target):d}
function showMessage(text,error=false){const m=$('message');m.textContent=text;m.classList.remove('hidden','error');if(error)m.classList.add('error')}
async function getPeriodReadiness(){
  if(!empresaId)return {ready:false,teams:0,people:0};
  const [teamsRes,peopleRes]=await Promise.all([
    db.from('equipes').select('*',{count:'exact',head:true}).eq('empresa_id',empresaId).eq('active',true),
    db.from('colaboradores').select('*',{count:'exact',head:true}).eq('empresa_id',empresaId).eq('active',true)
  ]);
  if(teamsRes.error||peopleRes.error)throw(teamsRes.error||peopleRes.error);
  const teams=teamsRes.count||0,people=peopleRes.count||0;
  return {ready:teams>0&&people>0,teams,people};
}
function renderPeriods(rows){const body=$('period-list');if(!rows.length){body.innerHTML='<tr><td colspan="5" class="empty">No periods have been prepared yet.</td></tr>';return}const latest=rows.reduce((a,b)=>new Date(a.start_date+'T00:00:00')>new Date(b.start_date+'T00:00:00')?a:b);body.innerHTML=rows.map((p,i)=>{const open=p.status==='ABERTO'||p.status==='OPEN';const canDelete=open&&p.id===latest.id;const action=canDelete?`<button class="delete-period-btn" data-period-id="${p.id}" data-week="${p.week_number}">Delete</button>`:'<span class="action-locked">—</span>';return `<tr><td><strong>Week ${p.week_number??i+1}</strong></td><td>${fmtDate(p.start_date)} → ${fmtDate(p.end_date)}</td><td><span class="period-status">${p.status==='ABERTO'?'OPEN':p.status==='FECHADO'?'CLOSED':p.status==='CANCELADO'?'CANCELLED':(p.status||'OPEN')}</span></td><td>${p.created_at?new Date(p.created_at).toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'}):'—'}</td><td>${action}</td></tr>`}).join('');body.querySelectorAll('.delete-period-btn').forEach(btn=>btn.addEventListener('click',()=>deletePeriod(btn.dataset.periodId,btn.dataset.week)))}
async function load(){const{data:{session},error:se}=await db.auth.getSession();if(se||!session?.user){location.href='index.html';return}const{data:user,error:ue}=await db.from('usuarios').select('id,name,empresa_id').eq('id',session.user.id).maybeSingle();if(ue||!user?.empresa_id){showMessage('Unable to load workspace profile.',true);return}empresaId=user.empresa_id;
const readiness=await getPeriodReadiness();
if(!readiness.ready){
  const missing=[];
  if(!readiness.teams)missing.push('at least one active Team');
  if(!readiness.people)missing.push('at least one active Person');
  $('prepare-btn').disabled=true;
  $('prepare-btn').title='Complete workspace readiness before preparing a period.';
  showMessage('Periods is locked until you have '+missing.join(' and ')+'.',true);
  $('cycle-name').textContent='Workspace not ready for Periods';
  $('cycle-meta').textContent='Create your Team and add People first. Period preparation will unlock automatically.';
  $('cycle-status').textContent='LOCKED';
  $('active-period').textContent='—';
  $('active-dates').textContent='Complete workspace readiness first';
  $('period-list').innerHTML='<tr><td colspan="5" class="empty">Periods will be available after at least one active Team and one active Person are registered.</td></tr>';
  return;
}
const name=user.name||session.user.user_metadata?.full_name||'Owner';const initial=name.trim().charAt(0).toUpperCase()||'O';$('user-name').textContent=name;$('user-email').textContent=session.user.email||'';$('user-avatar').textContent=initial;$('menu-avatar').textContent=initial;$('menu-full-name').textContent=name;$('menu-full-email').textContent=session.user.email||'';const[cr,br]=await Promise.all([db.from('configuracoes_operacionais').select('*').eq('empresa_id',empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle(),db.from('bonus_cycles').select('*').eq('empresa_id',empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(cr.error||br.error){showMessage('Unable to load cycle configuration.',true);return}config=cr.data;cycle=br.data;if(!cycle){$('cycle-name').textContent='No Bonus Cycle configured';$('cycle-meta').textContent='Complete Workspace Setup before preparing a period.';$('prepare-btn').disabled=true;renderPeriods([]);return}const frequency=config?.evaluation_frequency||'WEEKLY';$('cycle-name').textContent=cycle.name;$('cycle-meta').textContent=`${cycle.year} · ${new Date(cycle.year,cycle.start_month-1).toLocaleDateString('en-US',{month:'long'})} → ${new Date(cycle.year,cycle.end_month-1).toLocaleDateString('en-US',{month:'long'})} · ${frequency==='WEEKLY'?'Weekly':frequency}`;$('cycle-status').textContent=cycle.status||'OPEN';$('starting-points').textContent=(cycle.starting_points??config?.starting_points??'—').toLocaleString?.('en-US')??'—';const people=await db.from('colaboradores').select('id,active').eq('empresa_id',empresaId);$('people-count').textContent=(people.data||[]).filter(p=>p.active).length;const periods=await db.from('periodos').select('id,start_date,end_date,year,week_number,status,created_at').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).order('start_date',{ascending:false});if(periods.error){showMessage(`Unable to load periods. ${periods.error.message}`,true);return}$('period-count').textContent=periods.data?.length||0;const active=(periods.data||[]).find(p=>p.status==='ABERTO');if(active){$('active-period').textContent=`Week ${active.week_number}`;$('active-dates').textContent=`${fmtDate(active.start_date)} → ${fmtDate(active.end_date)}`}else{$('active-period').textContent='—';$('active-dates').textContent='No period prepared'}renderPeriods(periods.data||[])}
async function deletePeriod(periodId,week){const first=confirm(`Delete Week ${week}?\n\nThis action will permanently remove the period and all prepared evaluation records for it. This cannot be undone.`);if(!first)return;const second=confirm(`Final confirmation: delete Week ${week}?\n\nOnly the latest OPEN period can be deleted.`);if(!second)return;showMessage('Deleting period...');try{const{data,error}=await db.rpc('delete_latest_open_period',{p_period_id:periodId,p_empresa_id:empresaId});if(error)throw error;if(!data?.deleted)throw new Error('Period could not be deleted.');showMessage(`Week ${week} deleted successfully.`);await load()}catch(e){console.error(e);showMessage(e.message||'Unable to delete period.',true)}}
async function prepareNextPeriod(){
  const readiness=await getPeriodReadiness();
  if(!readiness.ready){
    const missing=[];
    if(!readiness.teams)missing.push('create your first Team');
    if(!readiness.people)missing.push('add your first Person');
    showMessage('Periods is not available yet. Please '+missing.join(' and ')+' first.',true);
    return;
  }
  if(!cycle||!config){showMessage('Complete the Bonus Cycle and Evaluation Period configuration first.',true);return}const btn=$('prepare-btn');btn.disabled=true;btn.textContent='Preparing...';try{if(config.evaluation_frequency!=='WEEKLY')throw new Error('The first period generator supports Weekly cycles.');const existing=await db.from('periodos').select('id,start_date,end_date,week_number').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).order('end_date',{ascending:false});if(existing.error)throw existing.error;let start,weekNumber;if(existing.data?.length){const latest=existing.data[0];start=new Date(latest.end_date+'T00:00:00');start.setDate(start.getDate()+1);start=nextDayOnOrAfter(start,Number(config.period_start_day));weekNumber=Math.max(...existing.data.map(p=>Number(p.week_number)||0))+1;}else{start=nextConfiguredPeriodStart();weekNumber=1;}const end=new Date(start);const delta=(Number(config.period_end_day)-start.getDay()+7)%7;end.setDate(end.getDate()+delta);if(start<cycleStartDate()||start>cycleEndDate()||end>cycleEndDate())throw new Error('There is no complete weekly period remaining inside this Bonus Cycle.');const startDate=dateOnly(start),endDate=dateOnly(end);const duplicate=await db.from('periodos').select('id').eq('empresa_id',empresaId).eq('bonus_cycle_id',cycle.id).eq('start_date',startDate).maybeSingle();if(duplicate.error)throw duplicate.error;if(duplicate.data)throw new Error('This weekly period already exists.');const insert={empresa_id:empresaId,start_date:startDate,end_date:endDate,year:start.getFullYear(),week_number:weekNumber,status:'ABERTO',bonus_cycle_id:cycle.id};const created=await db.from('periodos').insert(insert).select('id,start_date,end_date,week_number,status').single();if(created.error)throw created.error;const targetPeriod=created.data;const prep=await db.rpc('prepare_period_evaluations',{p_period_id:targetPeriod.id,p_empresa_id:empresaId,p_avaliador_id:null});if(prep.error)throw prep.error;const result=prep.data||{};showMessage(`Period ready: ${fmtDate(targetPeriod.start_date)} → ${fmtDate(targetPeriod.end_date)} · ${result.people_created||0} people · ${result.occurrences_created||0} occurrences.`);await load();}catch(e){console.error(e);showMessage(e.message||'Unable to prepare the next period.',true)}finally{btn.disabled=false;btn.textContent='Prepare Next Period →'}}
$('prepare-btn').addEventListener('click',prepareNextPeriod);$('user-menu-btn').addEventListener('click',e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')});document.addEventListener('click',e=>{if(!e.target.closest('.user-menu-wrap'))$('user-menu').classList.add('hidden')});$('menu-logout').addEventListener('click',async()=>{await db.auth.signOut();location.href='index.html'});load();