const { url, publishableKey } = window.KORBUILD_SUPABASE;
const db = window.supabase.createClient(url, publishableKey, { auth: { persistSession: true, autoRefreshToken: true } });
const state = { step: 2, maxPoints: 500, pointValue: 1.00, cycleName: 'Annual Performance 2027', cycleStart: 'January', cycleEnd: 'December', frequency: 'WEEKLY', startDay: '1', endDay: '6', preparation: 'MANUAL', preparationDay: '6', preparationTime: '08:00', empresaId: null };
const $ = id => document.getElementById(id);
const views = [...document.querySelectorAll('.step-view')];
const labels = [...document.querySelectorAll('.progress-labels span')];
const monthNumber = name => ({January:1,February:2,March:3,April:4,May:5,June:6,July:7,August:8,September:9,October:10,November:11,December:12}[name]);
const monthName = value => ({1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'}[Number(value)] || 'January');
const dayName = v => ({0:'Sunday',1:'Monday',2:'Tuesday',3:'Wednesday',4:'Thursday',5:'Friday',6:'Saturday'}[v]);
const freqName = v => ({WEEKLY:'Weekly',BIWEEKLY:'Every 2 weeks',MONTHLY:'Monthly'}[v] || v);
function collect(){if(state.step===2){state.maxPoints=Number($('max-points').value);state.pointValue=Number($('point-value').value)}if(state.step===3){state.cycleName=$('cycle-name').value.trim()||'Annual Performance 2027';state.cycleStart=$('cycle-start').value;state.cycleEnd=$('cycle-end').value}if(state.step===4){state.frequency=$('frequency').value;state.startDay=$('start-day').value;state.endDay=$('end-day').value;state.preparation=document.querySelector('input[name="preparation"]:checked')?.value||'MANUAL';state.preparationDay=$('prep-day').value;state.preparationTime=$('prep-time').value}}
function updatePreparationUI(){const automatic=document.querySelector('input[name="preparation"]:checked')?.value==='AUTOMATIC';$('automatic-options')?.classList.toggle('hidden',!automatic);const day=$('prep-day'),time=$('prep-time');if(day)day.disabled=!automatic;if(time)time.disabled=!automatic}
function updateSummary(){$('summary-evaluation').textContent=`${state.maxPoints} points · $${state.pointValue.toFixed(2)} / point`;$('summary-cycle').textContent=state.cycleName;$('summary-cycle-dates').textContent=`${state.cycleStart} → ${state.cycleEnd}`;$('summary-period').textContent=`${freqName(state.frequency)} · ${dayName(state.startDay)} → ${dayName(state.endDay)}`;$('summary-prep').textContent=state.preparation==='AUTOMATIC'?`Automatic · ${dayName(state.preparationDay)} at ${state.preparationTime}`:'Manual preparation'}
function render(){views.forEach(v=>v.classList.toggle('hidden',Number(v.dataset.step)!==state.step));$('step-number').textContent=state.step;$('progress-bar').style.width=`${((state.step-1)/6)*100}%`;labels.forEach((label,i)=>{label.classList.toggle('done',i<state.step-1);label.classList.toggle('active',i===state.step-1)});$('back').disabled=state.step<=2;$('next').classList.toggle('hidden',state.step>=7);$('confirm').classList.toggle('hidden',state.step!==7);updatePreparationUI();if(state.step===7)updateSummary()}
function closeMenu(){$('user-menu')?.classList.add('hidden');$('user-menu-btn')?.setAttribute('aria-expanded','false')}
$('user-menu-btn')?.addEventListener('click',e=>{e.stopPropagation();const menu=$('user-menu');const hidden=menu.classList.toggle('hidden');$('user-menu-btn').setAttribute('aria-expanded',String(!hidden))});
document.addEventListener('click',e=>{if(!e.target.closest('.user-menu-wrap'))closeMenu()});
$('menu-dashboard')?.addEventListener('click',()=>window.location.href='home.html');
$('menu-logout')?.addEventListener('click',async()=>{await db.auth.signOut();window.location.href='index.html'});
document.querySelectorAll('input[name="preparation"]').forEach(input=>input.addEventListener('change',updatePreparationUI));
$('next').addEventListener('click',()=>{collect();if(state.step<7){state.step+=1;render()}});
$('back').addEventListener('click',()=>{collect();if(state.step>2){state.step-=1;render()}});
document.querySelectorAll('.edit-btn').forEach(btn=>btn.addEventListener('click',()=>{collect();state.step=Number(btn.dataset.edit);render()}));
async function getCurrentUser(){const{data:{session},error:sessionError}=await db.auth.getSession();if(sessionError||!session?.user){window.location.href='index.html';return null}const{data:profile,error:profileError}=await db.from('usuarios').select('id,name,empresa_id,active,empresas(name)').eq('id',session.user.id).maybeSingle();if(profileError||!profile?.empresa_id){alert('Unable to load your workspace profile.');return null}state.empresaId=profile.empresa_id;const company=profile.empresas?.name||'KORbuild Demo';$('workspace-name').textContent=company;const name=profile.name||session.user.user_metadata?.full_name||session.user.email?.split('@')[0]||'Owner';const initial=name.trim().charAt(0).toUpperCase()||'O';document.querySelectorAll('.user-avatar').forEach(el=>el.textContent=initial);$('menu-user-name').textContent=name;$('menu-full-name').textContent=name;$('menu-user-email').textContent=session.user.email||'';$('menu-full-email').textContent=session.user.email||'';return session.user}
async function loadSavedSetup(){const[{data:config,error:configError},{data:cycle,error:cycleError}]=await Promise.all([db.from('configuracoes_operacionais').select('*').eq('empresa_id',state.empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle(),db.from('bonus_cycles').select('*').eq('empresa_id',state.empresaId).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(configError)throw configError;if(cycleError)throw cycleError;if(config){state.maxPoints=Number(config.starting_points??state.maxPoints);state.pointValue=Number(config.point_value??state.pointValue);state.frequency=config.evaluation_frequency||state.frequency;state.startDay=String(config.period_start_day??state.startDay);state.endDay=String(config.period_end_day??state.endDay);state.preparation=config.period_preparation_mode||state.preparation;state.preparationDay=String(config.period_preparation_day??state.preparationDay);state.preparationTime=(config.period_preparation_time||state.preparationTime).toString().slice(0,5)}if(cycle){state.cycleName=cycle.name||state.cycleName;state.cycleStart=monthName(cycle.start_month);state.cycleEnd=monthName(cycle.end_month);const year=cycle.year?String(cycle.year):'';if(year&&!state.cycleName.match(/20\d{2}/))state.cycleName=`${state.cycleName} ${year}`}const saved=!!config&&!!cycle;if(saved)state.step=7;else if(config)state.step=2;const set=(id,value)=>{const el=$(id);if(el)el.value=value};set('max-points',state.maxPoints);set('point-value',state.pointValue.toFixed(2));set('cycle-name',state.cycleName);set('cycle-start',state.cycleStart);set('cycle-end',state.cycleEnd);set('frequency',state.frequency);set('start-day',state.startDay);set('end-day',state.endDay);set('prep-day',state.preparationDay);set('prep-time',state.preparationTime);const radio=document.querySelector(`input[name="preparation"][value="${state.preparation}"]`);if(radio)radio.checked=true}
async function persistSetup(){collect();if(!state.empresaId)throw new Error('Workspace not loaded.');if(!Number.isFinite(state.maxPoints)||state.maxPoints<1)throw new Error('Starting points must be at least 1.');if(!Number.isFinite(state.pointValue)||state.pointValue<0)throw new Error('Value per point cannot be negative.');const yearMatch=state.cycleName.match(/(20\d{2})/);const year=yearMatch?Number(yearMatch[1]):new Date().getFullYear();const config={empresa_id:state.empresaId,evaluation_frequency:state.frequency,period_start_day:Number(state.startDay),period_end_day:Number(state.endDay),evaluation_target:'ACTIVE_ONLY',period_preparation_mode:state.preparation,starting_points:state.maxPoints,point_value:state.pointValue,bonus_cycle_start_month:monthNumber(state.cycleStart),bonus_cycle_end_month:monthNumber(state.cycleEnd),period_preparation_day:Number(state.preparationDay),period_preparation_time:state.preparationTime};const{data:existingConfig,error:configReadError}=await db.from('configuracoes_operacionais').select('id').eq('empresa_id',state.empresaId).maybeSingle();if(configReadError)throw configReadError;let configError;if(existingConfig?.id){({error:configError}=await db.from('configuracoes_operacionais').update(config).eq('id',existingConfig.id));}else{({error:configError}=await db.from('configuracoes_operacionais').insert(config));}if(configError)throw configError;const{data:existingCycle,error:cycleReadError}=await db.from('bonus_cycles').select('id').eq('empresa_id',state.empresaId).eq('name',state.cycleName).eq('year',year).maybeSingle();if(cycleReadError)throw cycleReadError;if(!existingCycle){const{error:cycleError}=await db.from('bonus_cycles').insert({empresa_id:state.empresaId,name:state.cycleName,year,start_month:monthNumber(state.cycleStart),end_month:monthNumber(state.cycleEnd),starting_points:state.maxPoints,point_value:state.pointValue,status:'OPEN',opened_at:new Date().toISOString()});if(cycleError)throw cycleError}}
$('confirm').addEventListener('click',async()=>{const btn=$('confirm');btn.disabled=true;btn.innerHTML='Saving...';try{await persistSetup();window.location.href='home.html?setup=complete'}catch(error){console.error(error);alert(`We couldn't save the setup. ${error.message||'Please try again.'}`);btn.disabled=false;btn.innerHTML='Confirm & Start KORbuild <span>→</span>'}});
async function init(){const user=await getCurrentUser();if(!user)return;try{await loadSavedSetup()}catch(error){console.error('Unable to load saved setup',error)}render()}
init();