if(!window.KORBUILD_APP){const s=document.createElement('script');s.src='app-config.js?v=1.2';document.head.appendChild(s);}
const { url, publishableKey } = window.KORBUILD_SUPABASE;
const db = window.supabase.createClient(url, publishableKey, { auth: { persistSession: true, autoRefreshToken: true } });
const $=id=>document.getElementById(id); const state={empresaId:null,teams:[],people:[]};
function closeMenu(){$('user-menu')?.classList.add('hidden');$('user-menu-btn')?.setAttribute('aria-expanded','false')}
function showMessage(text,type='success'){const el=$('message');el.textContent=text;el.className=`message ${type}`;el.classList.remove('hidden')}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function formatDate(v){return v?new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—'}
function render(){const q=($('search').value||'').trim().toLowerCase();const rows=state.teams.filter(t=>!q||t.name.toLowerCase().includes(q));$('active-count').textContent=state.teams.filter(t=>t.active).length;$('inactive-count').textContent=state.teams.filter(t=>!t.active).length;$('assigned-count').textContent=state.people.filter(p=>p.active&&p.equipe_id).length;$('teams-body').innerHTML=rows.map(t=>{const count=state.people.filter(p=>p.active&&p.equipe_id===t.id).length;return `<tr><td><div class="team-name">${escapeHtml(t.name)}</div></td><td>${count}</td><td><span class="team-status ${t.active?'active':'inactive'}"><span class="dot"></span>${t.active?'Active':'Inactive'}</span></td><td>${formatDate(t.created_at)}</td><td><div class="row-actions"><button class="small-btn" data-action="toggle" data-id="${t.id}">${t.active?'Deactivate':'Activate'}</button></div></td></tr>`}).join('');$('empty-state').classList.toggle('hidden',rows.length>0)}
async function loadProfile(){const{data:{session},error}=await db.auth.getSession();if(error||!session?.user){location.href='index.html';return false}const{data:profile,error:profileError}=await db.from('usuarios').select('id,name,empresa_id,active,empresas(name)').eq('id',session.user.id).maybeSingle();if(profileError||!profile?.empresa_id){showMessage(profileError?.message||'Unable to load workspace profile.','error');return false}state.empresaId=profile.empresa_id;$('side-company').textContent=profile.empresas?.name||'KORbuild Demo';const company=profile.empresas?.name||'KORbuild Demo';const profileName=profile.name?.trim();const name=profileName&&profileName!=='Owner'?profileName:session.user.user_metadata?.full_name||`${company} Owner`;const initial=name.trim().charAt(0).toUpperCase()||'O';$('user-name').textContent=name;$('user-email').textContent=session.user.email||'';$('user-avatar').textContent=initial;$('menu-avatar').textContent=initial;$('menu-full-name').textContent=name;$('menu-full-email').textContent=session.user.email||'';return true}
async function loadData(){const[{data:teams,error:teamsError},{data:people,error:peopleError}]=await Promise.all([db.from('equipes').select('id,empresa_id,name,active,created_at').eq('empresa_id',state.empresaId).order('name',{ascending:true}),db.from('colaboradores').select('id,empresa_id,equipe_id,name,active').eq('empresa_id',state.empresaId)]);if(teamsError)throw teamsError;if(peopleError)throw peopleError;state.teams=teams||[];state.people=people||[];render()}
async function toggleTeam(id){const team=state.teams.find(t=>t.id===id);if(!team)return;const assigned=state.people.filter(p=>p.active&&p.equipe_id===id).length;if(team.active&&assigned>0){showMessage(`Cannot deactivate ${team.name} while ${assigned} active ${assigned===1?'person is':'people are'} assigned to it.`,'error');return}const{error}=await db.from('equipes').update({active:!team.active}).eq('id',id).eq('empresa_id',state.empresaId);if(error){showMessage(`We couldn't update this team. ${error.message}`,'error');return}await loadData();showMessage(`${team.name} is now ${!team.active?'active':'inactive'}.`)}
$('user-menu-btn')?.addEventListener('click',e=>{e.stopPropagation();const menu=$('user-menu');const hidden=menu.classList.toggle('hidden');$('user-menu-btn').setAttribute('aria-expanded',String(!hidden))});document.addEventListener('click',e=>{if(!e.target.closest('.user-menu-wrap'))closeMenu()});$('menu-logout')?.addEventListener('click',async()=>{await db.auth.signOut();location.href='index.html'});$('add-team').addEventListener('click',()=>{const name=prompt('Team name');if(!name?.trim())return;db.from('equipes').insert({empresa_id:state.empresaId,name:name.trim(),active:true}).then(async({error})=>{if(error)showMessage(`We couldn't create the team. ${error.message}`,'error');else{await loadData();showMessage('Team created successfully.')}})});$('search').addEventListener('input',render);$('teams-body').addEventListener('click',e=>{const btn=e.target.closest('button[data-action="toggle"]');if(btn)toggleTeam(btn.dataset.id)});async function init(){if(await loadProfile())try{await loadData()}catch(error){console.error(error);showMessage(`Unable to load Teams. ${error.message}`,'error')}}init();